### ISSUE TITLE
Routes are not being correctly matched by method

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/framework#173]

**Comment by thosakwe** [comment]
Turned out to be a caching issue.

**Comment by Rodsevich** [comment]
And how did you solve it?
I'm having a very similar one:
start server
GET /api/service
200 `[]`
POST /api/service {"foo":"bar}
200 `[]`

However if I restart and invert the order...
POST /api/service {"foo":"bar}
201 `{id:1,foo:"bar",created...}`
GET /api/service
201 `{id:1,created...}`

**Comment by thosakwe** [comment]
Version 1.0.8 and beyond is broken in that regard. The bug has been fixed in 1.1.0-alpha; however, that comes with some changes.

I will have to clone this separately on my computer, revert back in the history to 1.0.10, and then patch it with a hot fix of sorts. It'll be 1.0.11, with no new features - just bugfixes for the existing infrastructure. I'll get this out within 24 hours.

**Comment by thosakwe** [comment]
Basically, there is a "handlerCache" that maps request paths to resolved routes, to save processing power. However, the original implementation didn't keep the request method in mind, so that's what causes this bug. Pesky, I know. 

The worst part is that this escaped tests. In the routing tests, a new server is created for every test, instead of sharing one instance, so there wasn't a check to make sure this wasn't in place.

**Comment by thosakwe** [comment]
@Rodsevich Sorry I took *way* too long to get to this, but the bug is patched in `package:angel_framework@1.0.11`.

**Comment by Rodsevich** [comment]
Thank you so much
