### ISSUE TITLE
`executeHandler` tries to encode too many things

### ISSUE THREAD

**Issue by daniel-v** [angel-dart/framework#194]
Erroneous use-case for: 
https://github.com/angel-dart/framework/blob/master/lib/src/core/server.dart#L310

```dart
app.get('/sum-content', 'just some string');
```

I just want to return this string as-is. Strings are json-encodable, however it should not be encoded, there are no indication that Angel should. For that, there is the `ResponseContextn.json()` method.

I believe the correct way to handle this would be:
- serialize, only if such response header is indicated
- strings should not be serialized by default
- default content-type should be `text/plain`

I consider this a critical error. (PR incoming)

**Comment by daniel-v** [comment]
Also, porting `angel_compress` to V1.1 is blocked by this issue.

Response finalizers can't modify header information on a response that has already been `closed` by serialize.

**Comment by thosakwe** [comment]
If you want to write a string to the response, you can do the following:

```dart
app.get('/foo', (res) => res.write('bar'));
```

My question is, if any other response is serialized by default, why should strings be an exception?

Also, the default content-type *is* `text/plain`. It becomes `application/json` when `json` is called.

**Comment by thosakwe** [comment]
Also, there is no need to port `angel_compress`, because in Angel v1.1, compression is handled internally by the framework. The current method (`injectEncoders`) encodes data both when using the response buffer and when writing directly to the underlying stream, whereas `angel_compress` is only capable of handling response buffers.

**Comment by daniel-v** [comment]
Hm... I suppose I was so focused on that 1-liner that I lost track of the bigger picture.

`in Angel v1.1, compression is handled internally `

Missed that.

`My question is, if any other response is serialized by default, why should strings be an exception?`

I *missed* something here as well: there is a default serializer set and all responses (unless null or bool) are serialized. 
And I *assumed* that there must be some kind of indication for Angel to serialize besides returning a value from a handler.

`Also, the default content-type is text/plain`

Depends where you look at it from. 

```dart
app.get('/sum-content', 'just some string');
```
Writing such a handler will give me a json encoded string with `application/json` content type by default.

```dart
app.get('/foo', (res) => res.write('bar'));
```
This will get me a `text/plain`.

Another couple of things to add to the Angel-know-how list. Issue can be closed, no point keeping it alive.

**Comment by thosakwe** [comment]
The good thing, though, is that there is room for lots of change in `1.2.0`. Just depends when it comes out.
