### ISSUE TITLE
RequestContext.accepts should return true if "Accepts" header is missing

### ISSUE THREAD

**Issue by davidosborn** [angel-dart/framework#238]
According to RFC 7321, a missing "Accept" header implies that the user agent will accept any media type in response. ```RequestContext.accepts``` returns ```false``` when the "Accept" header is missing, which is the opposite behaviour. This prevents the ```deserializer``` from being called after authenticating if the user agent does not include an "Accepts" header.

**Comment by thosakwe** [comment]
Thanks for pointing this out. Would you be interested in submitting a pull request to correct this?

**Comment by davidosborn** [comment]
Sure!

**Comment by thosakwe** [comment]
Here's the faulty line:
https://github.com/angel-dart/framework/blob/master/lib/src/core/request_context.dart#L213

**Comment by thosakwe** [comment]
Resolved via #239
