### ISSUE TITLE
Remove mirrors dependency? 

### ISSUE THREAD

**Issue by tabula-rasa** [angel-dart/framework#244]
Hy @thosakwe, do you have any plans on removing mirrors dep (ex. in quiver package)? Would be awesome for aot compilation.

**Comment by thosakwe** [comment]
This has already been done; Angel 2.0 has no `dart:mirrors` dependency whatsoever. Make sure you’re not using Jael, or `MirrorsReflector`.

**Comment by tabula-rasa** [comment]
But the framework uses quiver, that depends on mirrors, I just checked.

**Comment by thosakwe** [comment]
Only the hash code computation functionality from quiver is used. I’ve never run into an issue using `dart2aot` with Angel.

**Comment by thosakwe** [comment]
Previous discussion: https://github.com/angel-dart/angel/issues/103

**Comment by tabula-rasa** [comment]
Oh, may be I'm doing something wrong then, I run dart2aot bin/main.dart bin/main.dart.aot on a pretty basic demo app and it tells me error: import of dart:mirrors with --enable-mirrors=false

**Comment by thosakwe** [comment]
I’d have to see your code to know, but `package:angel_framework` doesn’t use `dart:mirrors`. If you used `angel init`, then you should definitely take a look at https://github.com/angel-dart/angel/issues/103.

**Comment by thosakwe** [comment]
As an added note, there’s no `quiver` dependency, only `quiver_hashcode`: https://github.com/angel-dart/framework/blob/master/pubspec.yaml

**Comment by tabula-rasa** [comment]
Sounds interesting, this is my repo, I have read the conversation, but it still does not work: [https://github.com/denisbakhtin/hello_angel](https://github.com/denisbakhtin/hello_angel)

**Comment by thosakwe** [comment]
`angel_hot` isn’t intended for AOT use, it’s development-only. Also, I highly doubt it will work at all, since hot reload is VM-only.

**Comment by tabula-rasa** [comment]
Ok i will try without it :)

**Comment by tabula-rasa** [comment]
Yes, angel_hot was the reason, thank you for explanation!
