### ISSUE TITLE
NoSuchMethodError: The getter 'address' was called on null.

### ISSUE THREAD

**Issue by u007** [angel-dart/framework#250]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/168.

**Comment by thosakwe** [comment]
Seems like you haven't called `AngelHttp.startServer`. Until you call this, calling `AngelHttp.uri` will throw. That's the error here.

**Comment by u007** [comment]
hI @thosakwe yes i did, was using hot reload
```
var hot = new HotReloader(createServer, [
    new Directory('lib'),
    new Directory('bin'),
    new Directory('config'),
    'bin/dev.dart',
    Uri.parse('package:angel_hot/angel_hot.dart')
  ]);

  await hot.startServer('localhost', 3060);
```
